# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  #name: 'default'
  name: 'Private-Build-Agent'

stages:
- stage: BuildAndScan
  jobs:
  - job: Scan
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
    - powershell: |
        Start-Sleep -Seconds 300
      displayName: 'Wait for 300 seconds'

#- stage: ApprovalStage
#  displayName: 'Report PipelineStatus'
#  jobs:
#  - job: ReportStatus
#    condition: always()
#    steps:
#    - checkout: none
#    - script: |      
#        curl -L \
#          -X POST \
#          -H "Accept: application/vnd.github+json" \
#          -H "Authorization: Bearer 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" \
#          -H "X-GitHub-Api-Version: 2022-11-28" \
#          https://api.github.com/repos/rvmsswt002/Azurepipelineactions/status