# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: 'default'

stages:
- stage: BuildAndScan
  jobs:
  - job: Scan
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
    - powershell: |
        Start-Sleep -Seconds 3
      displayName: 'Wait for 300 seconds'

- stage: ApprovalStage
  displayName: 'Report PipelineStatus'
  jobs:
  - job: ReportStatus
    condition: always()
    steps:
    - checkout: none
    - bash: |      
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/rvmsswt002/Application10/statuses/78965a0dd2690249f4e2028af9c4c4e28baed9e0 \